eureka:
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: 'true'
server:
  port: 8081
  tomcat:
    relaxed-query-chars: <,>,[,\,],^,`,{,|,}
    relaxed-path-chars: <,>,[,\,],^,`,{,|,}
spring:
  application:
    name: usuario
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher




