server:
  tomcat:
    relaxed-query-chars: <,>,[,\,],^,`,{,|,}
    relaxed-path-chars: <,>,[,\,],^,`,{,|,}
  servlet:
    context-path: /api
  port: '8080'
eureka:
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: 'true'
spring:
  application:
    name: empresa
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
