server:
  port: '8081'
spring:
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/TestRealm/protocol/openid-connect/certs
