eureka:
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: 'true'
server:
  tomcat:
    relaxed-query-chars: <,>,[,\,],^,`,{,|,}
    relaxed-path-chars: <,>,[,\,],^,`,{,|,}
  # servlet:
  #   context-path: /api
spring:
  application:
    name: empresa
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/SpringMicroservices/protocol/openid-connect/certs



    