server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          searchLocations: C:\Users\mds_s\Documents\src\SpringMicroservices\config
  profiles:
    active: native
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/TestRealm/protocol/openid-connect/certs

